version: '3'
services:
  api:
    build:
      context: ./Server
      dockerfile: ../docker/server/Dockerfile
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
       - ./Server:/app/server
       - /server/node_modules
    networks:
      - internal
      - private

  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./client:/app/client
       - /client/node_modules
    networks:
      - private

  db:
    image: postgres:14.1-alpine
    container_name: postgres-db-server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    env_file:
      - ./docker/db/.env
    networks:
      - internal
    ports:
      - "5432:5432"

networks:
  internal:
    external: false
  private:
    external: true